### ISSUE TITLE
Milestone 1

### ISSUE THREAD

**Issue by magnus-madsen** [flix/vscode-flix#14]
Client:
- [x] Basic syntax highlighting
- [x] Diagnostics
- [x] Commands
- [x] Shutdown - Send shutdown to compiler on de-activate.
- [x] Hover
- [x] Goto
- [x] Find references
- [x] CodeLenses (specifically RunMain, RunAllTests)
- [x] Show version tooltip when started.
- [x] Support multiple instances with multiple ports ...
- [x] Check Java version
- [x] Download hardcoded version (if not already downloaded and not flix.jar in project folder).
- [x] Add command to re-download jar. (add current.jar to nightly?)
- [x] Recover/restart from hard crash.
- [x] Make robust in face of general errors.
- [x] Debounce when typing. 
- [x] Build a vsix package that actually works.
- [x] Remove SelectionRangeRequest
- [x] Remove Document Symbol Request
- [x] Remove FoldingRangeRequest
- [x] Remove Completion

Compiler:
- [x] Remove SelectionRangeRequest
- [x] Remove Document Symbol Request
- [x] Remove FoldingRangeRequest
- [x] Remove Completion

Other:
- [x] MS marketplace (MM)
- [x] Readme (MM)

**Comment by magnus-madsen** [comment]
I moved rename request to milestone 2. I want to narrow the focus and get something releasable.

**Comment by magnus-madsen** [comment]
I moved Document Highlights Request to milestone 2.

**Comment by plougsgaard** [comment]
- Recover/restart from hard crash.
  - Currently we try to restart the plugin when Flix writes to `stderr` (vscode has a built-in max of 5 restarts, so it's "safe")

**Comment by magnus-madsen** [comment]
Yay, we did it! Now let the money roll in: https://github.com/flix/flix/issues/1374
