### ISSUE TITLE
Milestone 2

### ISSUE THREAD

**Issue by magnus-madsen** [flix/vscode-flix#15]
The plan is to select a subset of these for milestone 2 (based on user feedback):

- [x] Console/terminal/window output of run main, run benchmarks, and run tests. (#6)
- [x] Download with progress bar. (#9)
- [x] Package commands. (#12, but see #26)
- [x] Goto Def for Std Lib should show a notification (#19)
- [x] Syntax highlighting fixes (#20)
- [x] Installation and upgrade story. (#49)
- [x] Multiple outputs (#27)
- [x] Spinners (#28)
- [x] Full-length Error messages (#35 - compiler support added in https://github.com/flix/flix/pull/1401)
- [x] Document Highlights Request (#47 - compiler support added in https://github.com/flix/flix/pull/1394)
- [x] Rename Support (#46 - compiler support added in https://github.com/flix/flix/pull/1390)

**Comment by magnus-madsen** [comment]
I would like to consider Milestone 2 as version 1.0 of the plugin.
