### ISSUE TITLE
Milestone 3

### ISSUE THREAD

**Issue by magnus-madsen** [flix/vscode-flix#23]
Resolve the following issues in prioritized order:

- [ ] Prompt and reconnect on socket close (#62 / #69 / #79 / #85)
- [x] Notifications for Main and Tests (#54)
- [x] Stdout and stderr (#39 / #86)
- [x] Recover from crashing flix program #87 
- [x] Use JAVA_HOME (#72)
- [x] Configure debounce (#66)
- [ ] Rename does not work (#67)

**Comment by magnus-madsen** [comment]
I have added some tests to `/test/` that can be used for debugging.

**Comment by magnus-madsen** [comment]
Do you have a time table for the remaining tickets? :)

**Comment by plougsgaard** [comment]
@magnus-madsen I've looked at using JAVA_HOME and don't think it's feasible to support. If the user wants a specific `java` they should just make sure it's in their `PATH`.

**Comment by magnus-madsen** [comment]
@plougsgaard OK. We should test that setting a different java in path works.
